### ISSUE TITLE
Stop using sudo in .travis.yml

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#927]
Instead of `sudo apt-get package` we should do
```yaml
sudo: false
addons:
    apt:
        package1
        package2
```
I heard rumors that it's faster, too.
